name = "magento-cloudflare-workers"
# type = "javascript"

account_id = "5cb000f66e410934794e2955a9cb17af"
workers_dev = true
compatibility_date = "2024-01-01"

# Optional: define specific entry points
# Uncomment the one you want to deploy
main = "src/caching.js"
# main = "src/geo-redirect.js"
# main = "src/bot-protection.js"
# main = "src/image-optimization.js"
# main = "src/maintenance-mode.js"
# main = "src/api-cache.js"

[[kv_namespaces]]
binding = "MAGENTO_KV"         # JS binding name
id = "690a18d714744d79b3162bff025c69b0"    # Get this from Cloudflare dashboard
